# Generated by Django 5.0.4 on 2024-04-26 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': '1. Customers',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=10, null=True)),
                ('waist', models.CharField(max_length=10, null=True)),
                ('amount', models.FloatField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.customers')),
            ],
            options={
                'verbose_name_plural': '2.Measurement',
            },
        ),
    ]
