# Generated by Django 5.0.4 on 2024-05-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='length',
            new_name='len',
        ),
    ]
