# Generated by Django 5.0.4 on 2024-05-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_rename_length_measurement_len'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='mobile',
            new_name='mobile_no',
        ),
    ]
